server:
  port: 9000
spring:
  application:
    name: spring-cloud-eureka
  boot:
    admin:
      client:
        url: http://localhost:9001
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: false # 是否拉取其它服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:${server.port}/eureka
