server:
  port: 9001
spring:
  application:
    name: spring-cloud-boot-admin
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
  instance:
    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*' # health,info