server:
  port: 8081
spring:
  application:
    name: spring-cloud-user
  boot:
    admin:
      client:
        url: http://localhost:9001
  zipkin:
    base-url: http://localhost:9411
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud?useSSL=false
    username: root
    password: 123456
mybatis:
  type-aliases-package: cn.tellsea.user.bean
logging:
  level:
    cn.tellsea.user.mapper: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
  instance:
    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    lease-renewal-interval-in-seconds: 30 # 30秒检测一次心跳
    lease-expiration-duration-in-seconds: 90 # 最小过期时长，间隔90秒就准备剔除，之后60秒后执行
swagger:
  base-package: cn.tellsea.user.web
